// Code generated by tool; DO NOT EDIT.

package p

import "fmt"

func generatedExample() {
	// This call is in a generated file and must not be flagged.
	_ = fmt.Errorf("static error in generated code")
}
