import { describe, expect, it, vi, afterEach, beforeEach } from "vitest";
import { cleanup, render, screen, waitFor } from "@testing-library/svelte";
import { userEvent } from "@testing-library/user-event";
import type { AIEnrichment } from "../../types";

vi.mock("lucide-svelte", () => ({
  Sparkles: () => {},
  Check: () => {},
  X: () => {},
}));

vi.mock("../../lib/api/core", () => ({
  ApiError: class ApiError extends Error {
    status: number;
    constructor(message: string, status: number) {
      super(message);
      this.status = status;
    }
  },
}));

const mockGetPendingAIEnrichment = vi.fn();
const mockApplyAIEnrichment = vi.fn();
const mockRejectAIEnrichment = vi.fn();

vi.mock("../../lib/api", () => ({
  getPendingAIEnrichment: (...args: unknown[]) =>
    mockGetPendingAIEnrichment(...args),
  applyAIEnrichment: (...args: unknown[]) => mockApplyAIEnrichment(...args),
  rejectAIEnrichment: (...args: unknown[]) => mockRejectAIEnrichment(...args),
}));

import AIEnrichmentPanel from "./AIEnrichmentPanel.svelte";
import { ApiError } from "../../lib/api/core";

const fakeEnrichment: AIEnrichment = {
  id: "ae1",
  book_id: "b1",
  status: "pending",
  provider: "openai",
  model: "gpt-4o-mini",
  suggested_tags: ["fantasy", "adventure"],
  reading_level: "Young Adult",
  generated_description: "A thrilling tale of adventure.",
  created_at: "2026-01-01T00:00:00Z",
  updated_at: "2026-01-01T00:00:00Z",
};

describe("AIEnrichmentPanel", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  afterEach(() => cleanup());

  it("shows a loading spinner initially", () => {
    mockGetPendingAIEnrichment.mockReturnValue(new Promise(() => {}));
    render(AIEnrichmentPanel, { bookId: "b1" });
    expect(screen.getByRole("status")).toBeInTheDocument();
    expect(
      screen.getByText("Checking for AI enrichment..."),
    ).toBeInTheDocument();
  });

  it("renders nothing when no pending enrichment exists (404)", async () => {
    mockGetPendingAIEnrichment.mockRejectedValue(
      new ApiError("Not Found", 404),
    );
    render(AIEnrichmentPanel, { bookId: "b1" });

    await waitFor(() => {
      expect(
        screen.queryByText("Checking for AI enrichment..."),
      ).not.toBeInTheDocument();
    });

    expect(screen.queryByTestId("ai-enrichment-panel")).not.toBeInTheDocument();
    expect(screen.queryByRole("alert")).not.toBeInTheDocument();
  });

  it("renders enrichment data when pending enrichment exists", async () => {
    mockGetPendingAIEnrichment.mockResolvedValue(fakeEnrichment);
    render(AIEnrichmentPanel, { bookId: "b1" });

    await waitFor(() => {
      expect(screen.getByText("AI Enrichment Review")).toBeInTheDocument();
    });

    expect(screen.getByText("fantasy")).toBeInTheDocument();
    expect(screen.getByText("adventure")).toBeInTheDocument();
    expect(screen.getByText("Young Adult")).toBeInTheDocument();
    expect(
      screen.getByText("A thrilling tale of adventure."),
    ).toBeInTheDocument();
    expect(
      screen.getByText("Generated by openai · gpt-4o-mini"),
    ).toBeInTheDocument();
  });

  it("renders Apply and Reject buttons", async () => {
    mockGetPendingAIEnrichment.mockResolvedValue(fakeEnrichment);
    render(AIEnrichmentPanel, { bookId: "b1" });

    await waitFor(() => {
      expect(screen.getByText("Apply")).toBeInTheDocument();
    });
    expect(screen.getByText("Reject")).toBeInTheDocument();
  });

  it("calls applyAIEnrichment and invokes onApplied callback on success", async () => {
    mockGetPendingAIEnrichment.mockResolvedValue(fakeEnrichment);
    mockApplyAIEnrichment.mockResolvedValue({
      ...fakeEnrichment,
      status: "applied",
    });
    const onApplied = vi.fn();

    const user = userEvent.setup();
    render(AIEnrichmentPanel, { bookId: "b1", onApplied });

    await waitFor(() => {
      expect(screen.getByText("Apply")).toBeInTheDocument();
    });

    await user.click(screen.getByText("Apply"));

    await waitFor(() => {
      expect(mockApplyAIEnrichment).toHaveBeenCalledWith("b1");
      expect(onApplied).toHaveBeenCalledOnce();
    });

    // Panel should disappear after applying
    expect(screen.queryByTestId("ai-enrichment-panel")).not.toBeInTheDocument();
  });

  it("calls rejectAIEnrichment and invokes onRejected callback on success", async () => {
    mockGetPendingAIEnrichment.mockResolvedValue(fakeEnrichment);
    mockRejectAIEnrichment.mockResolvedValue(undefined);
    const onRejected = vi.fn();

    const user = userEvent.setup();
    render(AIEnrichmentPanel, { bookId: "b1", onRejected });

    await waitFor(() => {
      expect(screen.getByText("Reject")).toBeInTheDocument();
    });

    await user.click(screen.getByText("Reject"));

    await waitFor(() => {
      expect(mockRejectAIEnrichment).toHaveBeenCalledWith("b1");
      expect(onRejected).toHaveBeenCalledOnce();
    });

    // Panel should disappear after rejecting
    expect(screen.queryByTestId("ai-enrichment-panel")).not.toBeInTheDocument();
  });

  it("shows an error message when initial load fails with a non-404 error", async () => {
    mockGetPendingAIEnrichment.mockRejectedValue(
      new Error("Internal Server Error"),
    );
    render(AIEnrichmentPanel, { bookId: "b1" });

    await waitFor(() => {
      expect(screen.getByText("Internal Server Error")).toBeInTheDocument();
    });
  });

  it("shows an error inside the panel when apply fails", async () => {
    mockGetPendingAIEnrichment.mockResolvedValue(fakeEnrichment);
    mockApplyAIEnrichment.mockRejectedValue(new Error("Apply failed"));

    const user = userEvent.setup();
    render(AIEnrichmentPanel, { bookId: "b1" });

    await waitFor(() => {
      expect(screen.getByText("Apply")).toBeInTheDocument();
    });

    await user.click(screen.getByText("Apply"));

    await waitFor(() => {
      expect(screen.getByText("Apply failed")).toBeInTheDocument();
    });

    // Panel should still be visible so the user can retry
    expect(screen.getByTestId("ai-enrichment-panel")).toBeInTheDocument();
  });

  it("shows an error inside the panel when reject fails", async () => {
    mockGetPendingAIEnrichment.mockResolvedValue(fakeEnrichment);
    mockRejectAIEnrichment.mockRejectedValue(new Error("Reject failed"));

    const user = userEvent.setup();
    render(AIEnrichmentPanel, { bookId: "b1" });

    await waitFor(() => {
      expect(screen.getByText("Reject")).toBeInTheDocument();
    });

    await user.click(screen.getByText("Reject"));

    await waitFor(() => {
      expect(screen.getByText("Reject failed")).toBeInTheDocument();
    });

    expect(screen.getByTestId("ai-enrichment-panel")).toBeInTheDocument();
  });

  it("disables both buttons while applying", async () => {
    mockGetPendingAIEnrichment.mockResolvedValue(fakeEnrichment);
    let resolveApply!: () => void;
    mockApplyAIEnrichment.mockReturnValue(
      new Promise<void>((resolve) => {
        resolveApply = resolve;
      }),
    );

    const user = userEvent.setup();
    render(AIEnrichmentPanel, { bookId: "b1" });

    await waitFor(() => {
      expect(screen.getByText("Apply")).toBeInTheDocument();
    });

    await user.click(screen.getByText("Apply"));

    await waitFor(() => {
      expect(screen.getByText("Applying...")).toBeInTheDocument();
    });

    expect(screen.getByText("Applying...").closest("button")).toBeDisabled();
    expect(screen.getByText("Reject").closest("button")).toBeDisabled();

    resolveApply();
  });

  it("disables both buttons while rejecting", async () => {
    mockGetPendingAIEnrichment.mockResolvedValue(fakeEnrichment);
    let resolveReject!: () => void;
    mockRejectAIEnrichment.mockReturnValue(
      new Promise<void>((resolve) => {
        resolveReject = resolve;
      }),
    );

    const user = userEvent.setup();
    render(AIEnrichmentPanel, { bookId: "b1" });

    await waitFor(() => {
      expect(screen.getByText("Reject")).toBeInTheDocument();
    });

    await user.click(screen.getByText("Reject"));

    await waitFor(() => {
      expect(screen.getByText("Rejecting...")).toBeInTheDocument();
    });

    expect(screen.getByText("Apply").closest("button")).toBeDisabled();
    expect(screen.getByText("Rejecting...").closest("button")).toBeDisabled();

    resolveReject();
  });

  it("renders nothing when enrichment has no suggested tags, reading level, or description", async () => {
    const minimalEnrichment: AIEnrichment = {
      ...fakeEnrichment,
      suggested_tags: [],
      reading_level: null,
      generated_description: null,
    };
    mockGetPendingAIEnrichment.mockResolvedValue(minimalEnrichment);
    render(AIEnrichmentPanel, { bookId: "b1" });

    await waitFor(() => {
      expect(screen.getByText("AI Enrichment Review")).toBeInTheDocument();
    });

    expect(screen.queryByLabelText("Suggested tags")).not.toBeInTheDocument();
    expect(screen.queryByText("Reading Level")).not.toBeInTheDocument();
    expect(screen.queryByText("Generated Description")).not.toBeInTheDocument();
  });

  it("discards enrichment result when bookId changes before the request settles", async () => {
    let resolveFirst!: (value: AIEnrichment) => void;
    const firstRequest = new Promise<AIEnrichment>((resolve) => {
      resolveFirst = resolve;
    });
    mockGetPendingAIEnrichment
      .mockReturnValueOnce(firstRequest)
      .mockResolvedValue(null);

    const { rerender } = render(AIEnrichmentPanel, { bookId: "b1" });

    // Navigate to a different book before the first request settles
    await rerender({ bookId: "b2" });

    // Resolve the stale first request with b1's enrichment
    resolveFirst(fakeEnrichment);

    // Wait for b2's request (which returns null) to finish
    await waitFor(() => {
      expect(
        screen.queryByText("Checking for AI enrichment..."),
      ).not.toBeInTheDocument();
    });

    // b1's enrichment must not be displayed
    expect(screen.queryByTestId("ai-enrichment-panel")).not.toBeInTheDocument();
    expect(screen.queryByText("AI Enrichment Review")).not.toBeInTheDocument();
  });
});
