// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package goodreads

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/Khan/genqlient/graphql"
)

// GetBookByAsinGetBookByAsinBook includes the requested fields of the GraphQL type Book.
type GetBookByAsinGetBookByAsinBook struct {
	Work GetBookByAsinGetBookByAsinBookWork `json:"work"`
}

// GetWork returns GetBookByAsinGetBookByAsinBook.Work, and is useful for accessing the field via an interface.
func (v *GetBookByAsinGetBookByAsinBook) GetWork() GetBookByAsinGetBookByAsinBookWork { return v.Work }

// GetBookByAsinGetBookByAsinBookWork includes the requested fields of the GraphQL type Work.
type GetBookByAsinGetBookByAsinBookWork struct {
	Id       string                                     `json:"id"`
	LegacyId int64                                      `json:"legacyId"`
	Details  GetBookByAsinGetBookByAsinBookWorkDetails  `json:"details"`
	BestBook GetBookByAsinGetBookByAsinBookWorkBestBook `json:"bestBook"`
}

// GetId returns GetBookByAsinGetBookByAsinBookWork.Id, and is useful for accessing the field via an interface.
func (v *GetBookByAsinGetBookByAsinBookWork) GetId() string { return v.Id }

// GetLegacyId returns GetBookByAsinGetBookByAsinBookWork.LegacyId, and is useful for accessing the field via an interface.
func (v *GetBookByAsinGetBookByAsinBookWork) GetLegacyId() int64 { return v.LegacyId }

// GetDetails returns GetBookByAsinGetBookByAsinBookWork.Details, and is useful for accessing the field via an interface.
func (v *GetBookByAsinGetBookByAsinBookWork) GetDetails() GetBookByAsinGetBookByAsinBookWorkDetails {
	return v.Details
}

// GetBestBook returns GetBookByAsinGetBookByAsinBookWork.BestBook, and is useful for accessing the field via an interface.
func (v *GetBookByAsinGetBookByAsinBookWork) GetBestBook() GetBookByAsinGetBookByAsinBookWorkBestBook {
	return v.BestBook
}

// GetBookByAsinGetBookByAsinBookWorkBestBook includes the requested fields of the GraphQL type Book.
type GetBookByAsinGetBookByAsinBookWorkBestBook struct {
	Id                     string                                                                              `json:"id"`
	LegacyId               int64                                                                               `json:"legacyId"`
	ImageUrl               string                                                                              `json:"imageUrl"`
	Title                  string                                                                              `json:"title"`
	Details                GetBookByAsinGetBookByAsinBookWorkBestBookDetails                                   `json:"details"`
	PrimaryContributorEdge GetBookByAsinGetBookByAsinBookWorkBestBookPrimaryContributorEdgeBookContributorEdge `json:"primaryContributorEdge"`
}

// GetId returns GetBookByAsinGetBookByAsinBookWorkBestBook.Id, and is useful for accessing the field via an interface.
func (v *GetBookByAsinGetBookByAsinBookWorkBestBook) GetId() string { return v.Id }

// GetLegacyId returns GetBookByAsinGetBookByAsinBookWorkBestBook.LegacyId, and is useful for accessing the field via an interface.
func (v *GetBookByAsinGetBookByAsinBookWorkBestBook) GetLegacyId() int64 { return v.LegacyId }

// GetImageUrl returns GetBookByAsinGetBookByAsinBookWorkBestBook.ImageUrl, and is useful for accessing the field via an interface.
func (v *GetBookByAsinGetBookByAsinBookWorkBestBook) GetImageUrl() string { return v.ImageUrl }

// GetTitle returns GetBookByAsinGetBookByAsinBookWorkBestBook.Title, and is useful for accessing the field via an interface.
func (v *GetBookByAsinGetBookByAsinBookWorkBestBook) GetTitle() string { return v.Title }

// GetDetails returns GetBookByAsinGetBookByAsinBookWorkBestBook.Details, and is useful for accessing the field via an interface.
func (v *GetBookByAsinGetBookByAsinBookWorkBestBook) GetDetails() GetBookByAsinGetBookByAsinBookWorkBestBookDetails {
	return v.Details
}

// GetPrimaryContributorEdge returns GetBookByAsinGetBookByAsinBookWorkBestBook.PrimaryContributorEdge, and is useful for accessing the field via an interface.
func (v *GetBookByAsinGetBookByAsinBookWorkBestBook) GetPrimaryContributorEdge() GetBookByAsinGetBookByAsinBookWorkBestBookPrimaryContributorEdgeBookContributorEdge {
	return v.PrimaryContributorEdge
}

// GetBookByAsinGetBookByAsinBookWorkBestBookDetails includes the requested fields of the GraphQL type BookDetails.
type GetBookByAsinGetBookByAsinBookWorkBestBookDetails struct {
	Asin     string                                                    `json:"asin"`
	Isbn     string                                                    `json:"isbn"`
	Isbn13   string                                                    `json:"isbn13"`
	Language GetBookByAsinGetBookByAsinBookWorkBestBookDetailsLanguage `json:"language"`
	NumPages int64                                                     `json:"numPages"`
}

// GetAsin returns GetBookByAsinGetBookByAsinBookWorkBestBookDetails.Asin, and is useful for accessing the field via an interface.
func (v *GetBookByAsinGetBookByAsinBookWorkBestBookDetails) GetAsin() string { return v.Asin }

// GetIsbn returns GetBookByAsinGetBookByAsinBookWorkBestBookDetails.Isbn, and is useful for accessing the field via an interface.
func (v *GetBookByAsinGetBookByAsinBookWorkBestBookDetails) GetIsbn() string { return v.Isbn }

// GetIsbn13 returns GetBookByAsinGetBookByAsinBookWorkBestBookDetails.Isbn13, and is useful for accessing the field via an interface.
func (v *GetBookByAsinGetBookByAsinBookWorkBestBookDetails) GetIsbn13() string { return v.Isbn13 }

// GetLanguage returns GetBookByAsinGetBookByAsinBookWorkBestBookDetails.Language, and is useful for accessing the field via an interface.
func (v *GetBookByAsinGetBookByAsinBookWorkBestBookDetails) GetLanguage() GetBookByAsinGetBookByAsinBookWorkBestBookDetailsLanguage {
	return v.Language
}

// GetNumPages returns GetBookByAsinGetBookByAsinBookWorkBestBookDetails.NumPages, and is useful for accessing the field via an interface.
func (v *GetBookByAsinGetBookByAsinBookWorkBestBookDetails) GetNumPages() int64 { return v.NumPages }

// GetBookByAsinGetBookByAsinBookWorkBestBookDetailsLanguage includes the requested fields of the GraphQL type Language.
type GetBookByAsinGetBookByAsinBookWorkBestBookDetailsLanguage struct {
	Name string `json:"name"`
}

// GetName returns GetBookByAsinGetBookByAsinBookWorkBestBookDetailsLanguage.Name, and is useful for accessing the field via an interface.
func (v *GetBookByAsinGetBookByAsinBookWorkBestBookDetailsLanguage) GetName() string { return v.Name }

// GetBookByAsinGetBookByAsinBookWorkBestBookPrimaryContributorEdgeBookContributorEdge includes the requested fields of the GraphQL type BookContributorEdge.
type GetBookByAsinGetBookByAsinBookWorkBestBookPrimaryContributorEdgeBookContributorEdge struct {
	Role string                                                                                             `json:"role"`
	Node GetBookByAsinGetBookByAsinBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor `json:"node"`
}

// GetRole returns GetBookByAsinGetBookByAsinBookWorkBestBookPrimaryContributorEdgeBookContributorEdge.Role, and is useful for accessing the field via an interface.
func (v *GetBookByAsinGetBookByAsinBookWorkBestBookPrimaryContributorEdgeBookContributorEdge) GetRole() string {
	return v.Role
}

// GetNode returns GetBookByAsinGetBookByAsinBookWorkBestBookPrimaryContributorEdgeBookContributorEdge.Node, and is useful for accessing the field via an interface.
func (v *GetBookByAsinGetBookByAsinBookWorkBestBookPrimaryContributorEdgeBookContributorEdge) GetNode() GetBookByAsinGetBookByAsinBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor {
	return v.Node
}

// GetBookByAsinGetBookByAsinBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor includes the requested fields of the GraphQL type Contributor.
type GetBookByAsinGetBookByAsinBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor struct {
	Id              string `json:"id"`
	Name            string `json:"name"`
	LegacyId        int64  `json:"legacyId"`
	ProfileImageUrl string `json:"profileImageUrl"`
}

// GetId returns GetBookByAsinGetBookByAsinBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor.Id, and is useful for accessing the field via an interface.
func (v *GetBookByAsinGetBookByAsinBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor) GetId() string {
	return v.Id
}

// GetName returns GetBookByAsinGetBookByAsinBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor.Name, and is useful for accessing the field via an interface.
func (v *GetBookByAsinGetBookByAsinBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor) GetName() string {
	return v.Name
}

// GetLegacyId returns GetBookByAsinGetBookByAsinBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor.LegacyId, and is useful for accessing the field via an interface.
func (v *GetBookByAsinGetBookByAsinBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor) GetLegacyId() int64 {
	return v.LegacyId
}

// GetProfileImageUrl returns GetBookByAsinGetBookByAsinBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor.ProfileImageUrl, and is useful for accessing the field via an interface.
func (v *GetBookByAsinGetBookByAsinBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor) GetProfileImageUrl() string {
	return v.ProfileImageUrl
}

// GetBookByAsinGetBookByAsinBookWorkDetails includes the requested fields of the GraphQL type WorkDetails.
type GetBookByAsinGetBookByAsinBookWorkDetails struct {
	WebUrl        string `json:"webUrl"`
	OriginalTitle string `json:"originalTitle"`
}

// GetWebUrl returns GetBookByAsinGetBookByAsinBookWorkDetails.WebUrl, and is useful for accessing the field via an interface.
func (v *GetBookByAsinGetBookByAsinBookWorkDetails) GetWebUrl() string { return v.WebUrl }

// GetOriginalTitle returns GetBookByAsinGetBookByAsinBookWorkDetails.OriginalTitle, and is useful for accessing the field via an interface.
func (v *GetBookByAsinGetBookByAsinBookWorkDetails) GetOriginalTitle() string { return v.OriginalTitle }

// GetBookByAsinResponse is returned by GetBookByAsin on success.
type GetBookByAsinResponse struct {
	GetBookByAsin GetBookByAsinGetBookByAsinBook `json:"getBookByAsin"`
}

// GetGetBookByAsin returns GetBookByAsinResponse.GetBookByAsin, and is useful for accessing the field via an interface.
func (v *GetBookByAsinResponse) GetGetBookByAsin() GetBookByAsinGetBookByAsinBook {
	return v.GetBookByAsin
}

// GetBookByLegacyIdGetBookByLegacyIdBook includes the requested fields of the GraphQL type Book.
type GetBookByLegacyIdGetBookByLegacyIdBook struct {
	Work GetBookByLegacyIdGetBookByLegacyIdBookWork `json:"work"`
}

// GetWork returns GetBookByLegacyIdGetBookByLegacyIdBook.Work, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdGetBookByLegacyIdBook) GetWork() GetBookByLegacyIdGetBookByLegacyIdBookWork {
	return v.Work
}

// GetBookByLegacyIdGetBookByLegacyIdBookWork includes the requested fields of the GraphQL type Work.
type GetBookByLegacyIdGetBookByLegacyIdBookWork struct {
	Id       string                                             `json:"id"`
	LegacyId int64                                              `json:"legacyId"`
	Details  GetBookByLegacyIdGetBookByLegacyIdBookWorkDetails  `json:"details"`
	BestBook GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBook `json:"bestBook"`
}

// GetId returns GetBookByLegacyIdGetBookByLegacyIdBookWork.Id, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdGetBookByLegacyIdBookWork) GetId() string { return v.Id }

// GetLegacyId returns GetBookByLegacyIdGetBookByLegacyIdBookWork.LegacyId, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdGetBookByLegacyIdBookWork) GetLegacyId() int64 { return v.LegacyId }

// GetDetails returns GetBookByLegacyIdGetBookByLegacyIdBookWork.Details, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdGetBookByLegacyIdBookWork) GetDetails() GetBookByLegacyIdGetBookByLegacyIdBookWorkDetails {
	return v.Details
}

// GetBestBook returns GetBookByLegacyIdGetBookByLegacyIdBookWork.BestBook, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdGetBookByLegacyIdBookWork) GetBestBook() GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBook {
	return v.BestBook
}

// GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBook includes the requested fields of the GraphQL type Book.
type GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBook struct {
	Id                     string                                                                                      `json:"id"`
	LegacyId               int64                                                                                       `json:"legacyId"`
	ImageUrl               string                                                                                      `json:"imageUrl"`
	Title                  string                                                                                      `json:"title"`
	Details                GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookDetails                                   `json:"details"`
	PrimaryContributorEdge GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookPrimaryContributorEdgeBookContributorEdge `json:"primaryContributorEdge"`
}

// GetId returns GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBook.Id, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBook) GetId() string { return v.Id }

// GetLegacyId returns GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBook.LegacyId, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBook) GetLegacyId() int64 { return v.LegacyId }

// GetImageUrl returns GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBook.ImageUrl, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBook) GetImageUrl() string { return v.ImageUrl }

// GetTitle returns GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBook.Title, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBook) GetTitle() string { return v.Title }

// GetDetails returns GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBook.Details, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBook) GetDetails() GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookDetails {
	return v.Details
}

// GetPrimaryContributorEdge returns GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBook.PrimaryContributorEdge, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBook) GetPrimaryContributorEdge() GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookPrimaryContributorEdgeBookContributorEdge {
	return v.PrimaryContributorEdge
}

// GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookDetails includes the requested fields of the GraphQL type BookDetails.
type GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookDetails struct {
	Asin     string                                                            `json:"asin"`
	Isbn     string                                                            `json:"isbn"`
	Isbn13   string                                                            `json:"isbn13"`
	Language GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookDetailsLanguage `json:"language"`
	NumPages int64                                                             `json:"numPages"`
}

// GetAsin returns GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookDetails.Asin, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookDetails) GetAsin() string { return v.Asin }

// GetIsbn returns GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookDetails.Isbn, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookDetails) GetIsbn() string { return v.Isbn }

// GetIsbn13 returns GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookDetails.Isbn13, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookDetails) GetIsbn13() string {
	return v.Isbn13
}

// GetLanguage returns GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookDetails.Language, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookDetails) GetLanguage() GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookDetailsLanguage {
	return v.Language
}

// GetNumPages returns GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookDetails.NumPages, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookDetails) GetNumPages() int64 {
	return v.NumPages
}

// GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookDetailsLanguage includes the requested fields of the GraphQL type Language.
type GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookDetailsLanguage struct {
	Name string `json:"name"`
}

// GetName returns GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookDetailsLanguage.Name, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookDetailsLanguage) GetName() string {
	return v.Name
}

// GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookPrimaryContributorEdgeBookContributorEdge includes the requested fields of the GraphQL type BookContributorEdge.
type GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookPrimaryContributorEdgeBookContributorEdge struct {
	Role string                                                                                                     `json:"role"`
	Node GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor `json:"node"`
}

// GetRole returns GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookPrimaryContributorEdgeBookContributorEdge.Role, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookPrimaryContributorEdgeBookContributorEdge) GetRole() string {
	return v.Role
}

// GetNode returns GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookPrimaryContributorEdgeBookContributorEdge.Node, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookPrimaryContributorEdgeBookContributorEdge) GetNode() GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor {
	return v.Node
}

// GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor includes the requested fields of the GraphQL type Contributor.
type GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor struct {
	Id              string `json:"id"`
	Name            string `json:"name"`
	LegacyId        int64  `json:"legacyId"`
	ProfileImageUrl string `json:"profileImageUrl"`
}

// GetId returns GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor.Id, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor) GetId() string {
	return v.Id
}

// GetName returns GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor.Name, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor) GetName() string {
	return v.Name
}

// GetLegacyId returns GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor.LegacyId, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor) GetLegacyId() int64 {
	return v.LegacyId
}

// GetProfileImageUrl returns GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor.ProfileImageUrl, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdGetBookByLegacyIdBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor) GetProfileImageUrl() string {
	return v.ProfileImageUrl
}

// GetBookByLegacyIdGetBookByLegacyIdBookWorkDetails includes the requested fields of the GraphQL type WorkDetails.
type GetBookByLegacyIdGetBookByLegacyIdBookWorkDetails struct {
	WebUrl        string `json:"webUrl"`
	OriginalTitle string `json:"originalTitle"`
}

// GetWebUrl returns GetBookByLegacyIdGetBookByLegacyIdBookWorkDetails.WebUrl, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdGetBookByLegacyIdBookWorkDetails) GetWebUrl() string { return v.WebUrl }

// GetOriginalTitle returns GetBookByLegacyIdGetBookByLegacyIdBookWorkDetails.OriginalTitle, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdGetBookByLegacyIdBookWorkDetails) GetOriginalTitle() string {
	return v.OriginalTitle
}

// GetBookByLegacyIdResponse is returned by GetBookByLegacyId on success.
type GetBookByLegacyIdResponse struct {
	GetBookByLegacyId GetBookByLegacyIdGetBookByLegacyIdBook `json:"getBookByLegacyId"`
}

// GetGetBookByLegacyId returns GetBookByLegacyIdResponse.GetBookByLegacyId, and is useful for accessing the field via an interface.
func (v *GetBookByLegacyIdResponse) GetGetBookByLegacyId() GetBookByLegacyIdGetBookByLegacyIdBook {
	return v.GetBookByLegacyId
}

// SearchGetSearchSuggestionsSearchResultsConnection includes the requested fields of the GraphQL type SearchResultsConnection.
type SearchGetSearchSuggestionsSearchResultsConnection struct {
	TotalCount int64                                                                    `json:"totalCount"`
	Edges      []SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchResultEdge `json:"-"`
}

// GetTotalCount returns SearchGetSearchSuggestionsSearchResultsConnection.TotalCount, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnection) GetTotalCount() int64 {
	return v.TotalCount
}

// GetEdges returns SearchGetSearchSuggestionsSearchResultsConnection.Edges, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnection) GetEdges() []SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchResultEdge {
	return v.Edges
}

func (v *SearchGetSearchSuggestionsSearchResultsConnection) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*SearchGetSearchSuggestionsSearchResultsConnection
		Edges []json.RawMessage `json:"edges"`
		graphql.NoUnmarshalJSON
	}
	firstPass.SearchGetSearchSuggestionsSearchResultsConnection = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.Edges
		src := firstPass.Edges
		*dst = make(
			[]SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchResultEdge,
			len(src))
		for i, src := range src {
			dst := &(*dst)[i]
			if len(src) != 0 && string(src) != "null" {
				err = __unmarshalSearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchResultEdge(
					src, dst)
				if err != nil {
					return fmt.Errorf(
						"unable to unmarshal SearchGetSearchSuggestionsSearchResultsConnection.Edges: %w", err)
				}
			}
		}
	}
	return nil
}

type __premarshalSearchGetSearchSuggestionsSearchResultsConnection struct {
	TotalCount int64 `json:"totalCount"`

	Edges []json.RawMessage `json:"edges"`
}

func (v *SearchGetSearchSuggestionsSearchResultsConnection) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *SearchGetSearchSuggestionsSearchResultsConnection) __premarshalJSON() (*__premarshalSearchGetSearchSuggestionsSearchResultsConnection, error) {
	var retval __premarshalSearchGetSearchSuggestionsSearchResultsConnection

	retval.TotalCount = v.TotalCount
	{

		dst := &retval.Edges
		src := v.Edges
		*dst = make(
			[]json.RawMessage,
			len(src))
		for i, src := range src {
			dst := &(*dst)[i]
			var err error
			*dst, err = __marshalSearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchResultEdge(
				&src)
			if err != nil {
				return nil, fmt.Errorf(
					"unable to marshal SearchGetSearchSuggestionsSearchResultsConnection.Edges: %w", err)
			}
		}
	}
	return &retval, nil
}

// SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdge includes the requested fields of the GraphQL type SearchBookEdge.
type SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdge struct {
	Typename string                                                                       `json:"__typename"`
	Node     SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBook `json:"node"`
}

// GetTypename returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdge.Typename, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdge) GetTypename() string {
	return v.Typename
}

// GetNode returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdge.Node, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdge) GetNode() SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBook {
	return v.Node
}

// SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBook includes the requested fields of the GraphQL type Book.
type SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBook struct {
	Work SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWork `json:"work"`
}

// GetWork returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBook.Work, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBook) GetWork() SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWork {
	return v.Work
}

// SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWork includes the requested fields of the GraphQL type Work.
type SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWork struct {
	Id       string                                                                                   `json:"id"`
	LegacyId int64                                                                                    `json:"legacyId"`
	BestBook SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBook `json:"bestBook"`
	Typename string                                                                                   `json:"__typename"`
}

// GetId returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWork.Id, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWork) GetId() string {
	return v.Id
}

// GetLegacyId returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWork.LegacyId, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWork) GetLegacyId() int64 {
	return v.LegacyId
}

// GetBestBook returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWork.BestBook, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWork) GetBestBook() SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBook {
	return v.BestBook
}

// GetTypename returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWork.Typename, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWork) GetTypename() string {
	return v.Typename
}

// SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBook includes the requested fields of the GraphQL type Book.
type SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBook struct {
	Id                     string                                                                                                                            `json:"id"`
	LegacyId               int64                                                                                                                             `json:"legacyId"`
	ImageUrl               string                                                                                                                            `json:"imageUrl"`
	Title                  string                                                                                                                            `json:"title"`
	Details                SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookDetails                                   `json:"details"`
	PrimaryContributorEdge SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookPrimaryContributorEdgeBookContributorEdge `json:"primaryContributorEdge"`
	Typename               string                                                                                                                            `json:"__typename"`
}

// GetId returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBook.Id, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBook) GetId() string {
	return v.Id
}

// GetLegacyId returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBook.LegacyId, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBook) GetLegacyId() int64 {
	return v.LegacyId
}

// GetImageUrl returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBook.ImageUrl, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBook) GetImageUrl() string {
	return v.ImageUrl
}

// GetTitle returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBook.Title, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBook) GetTitle() string {
	return v.Title
}

// GetDetails returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBook.Details, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBook) GetDetails() SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookDetails {
	return v.Details
}

// GetPrimaryContributorEdge returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBook.PrimaryContributorEdge, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBook) GetPrimaryContributorEdge() SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookPrimaryContributorEdgeBookContributorEdge {
	return v.PrimaryContributorEdge
}

// GetTypename returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBook.Typename, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBook) GetTypename() string {
	return v.Typename
}

// SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookDetails includes the requested fields of the GraphQL type BookDetails.
type SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookDetails struct {
	Asin     string                                                                                                  `json:"asin"`
	Isbn     string                                                                                                  `json:"isbn"`
	Isbn13   string                                                                                                  `json:"isbn13"`
	Language SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookDetailsLanguage `json:"language"`
	NumPages int64                                                                                                   `json:"numPages"`
	Typename string                                                                                                  `json:"__typename"`
}

// GetAsin returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookDetails.Asin, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookDetails) GetAsin() string {
	return v.Asin
}

// GetIsbn returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookDetails.Isbn, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookDetails) GetIsbn() string {
	return v.Isbn
}

// GetIsbn13 returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookDetails.Isbn13, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookDetails) GetIsbn13() string {
	return v.Isbn13
}

// GetLanguage returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookDetails.Language, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookDetails) GetLanguage() SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookDetailsLanguage {
	return v.Language
}

// GetNumPages returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookDetails.NumPages, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookDetails) GetNumPages() int64 {
	return v.NumPages
}

// GetTypename returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookDetails.Typename, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookDetails) GetTypename() string {
	return v.Typename
}

// SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookDetailsLanguage includes the requested fields of the GraphQL type Language.
type SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookDetailsLanguage struct {
	Name     string `json:"name"`
	Typename string `json:"__typename"`
}

// GetName returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookDetailsLanguage.Name, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookDetailsLanguage) GetName() string {
	return v.Name
}

// GetTypename returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookDetailsLanguage.Typename, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookDetailsLanguage) GetTypename() string {
	return v.Typename
}

// SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookPrimaryContributorEdgeBookContributorEdge includes the requested fields of the GraphQL type BookContributorEdge.
type SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookPrimaryContributorEdgeBookContributorEdge struct {
	Role string                                                                                                                                           `json:"role"`
	Node SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor `json:"node"`
}

// GetRole returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookPrimaryContributorEdgeBookContributorEdge.Role, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookPrimaryContributorEdgeBookContributorEdge) GetRole() string {
	return v.Role
}

// GetNode returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookPrimaryContributorEdgeBookContributorEdge.Node, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookPrimaryContributorEdgeBookContributorEdge) GetNode() SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor {
	return v.Node
}

// SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor includes the requested fields of the GraphQL type Contributor.
type SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor struct {
	Id              string `json:"id"`
	Name            string `json:"name"`
	LegacyId        int64  `json:"legacyId"`
	ProfileImageUrl string `json:"profileImageUrl"`
	Typename        string `json:"__typename"`
}

// GetId returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor.Id, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor) GetId() string {
	return v.Id
}

// GetName returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor.Name, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor) GetName() string {
	return v.Name
}

// GetLegacyId returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor.LegacyId, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor) GetLegacyId() int64 {
	return v.LegacyId
}

// GetProfileImageUrl returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor.ProfileImageUrl, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor) GetProfileImageUrl() string {
	return v.ProfileImageUrl
}

// GetTypename returns SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor.Typename, and is useful for accessing the field via an interface.
func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdgeNodeBookWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor) GetTypename() string {
	return v.Typename
}

// SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchResultEdge includes the requested fields of the GraphQL interface SearchResultEdge.
//
// SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchResultEdge is implemented by the following types:
// SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdge
type SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchResultEdge interface {
	implementsGraphQLInterfaceSearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchResultEdge()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
}

func (v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdge) implementsGraphQLInterfaceSearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchResultEdge() {
}

func __unmarshalSearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchResultEdge(b []byte, v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchResultEdge) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "SearchBookEdge":
		*v = new(SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdge)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing SearchResultEdge.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchResultEdge: "%v"`, tn.TypeName)
	}
}

func __marshalSearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchResultEdge(v *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchResultEdge) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdge:
		typename = "SearchBookEdge"

		result := struct {
			TypeName string `json:"__typename"`
			*SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchBookEdge
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for SearchGetSearchSuggestionsSearchResultsConnectionEdgesSearchResultEdge: "%T"`, v)
	}
}

// SearchResponse is returned by Search on success.
type SearchResponse struct {
	GetSearchSuggestions SearchGetSearchSuggestionsSearchResultsConnection `json:"getSearchSuggestions"`
}

// GetGetSearchSuggestions returns SearchResponse.GetSearchSuggestions, and is useful for accessing the field via an interface.
func (v *SearchResponse) GetGetSearchSuggestions() SearchGetSearchSuggestionsSearchResultsConnection {
	return v.GetSearchSuggestions
}

// __GetBookByAsinInput is used internally by genqlient
type __GetBookByAsinInput struct {
	Asin string `json:"asin"`
}

// GetAsin returns __GetBookByAsinInput.Asin, and is useful for accessing the field via an interface.
func (v *__GetBookByAsinInput) GetAsin() string { return v.Asin }

// __GetBookByLegacyIdInput is used internally by genqlient
type __GetBookByLegacyIdInput struct {
	LegacyId int64 `json:"legacyId"`
}

// GetLegacyId returns __GetBookByLegacyIdInput.LegacyId, and is useful for accessing the field via an interface.
func (v *__GetBookByLegacyIdInput) GetLegacyId() int64 { return v.LegacyId }

// __SearchInput is used internally by genqlient
type __SearchInput struct {
	Query string `json:"query"`
}

// GetQuery returns __SearchInput.Query, and is useful for accessing the field via an interface.
func (v *__SearchInput) GetQuery() string { return v.Query }

// The query executed by GetBookByAsin.
const GetBookByAsin_Operation = `
query GetBookByAsin ($asin: String!) {
	getBookByAsin(asin: $asin) {
		work {
			id
			legacyId
			details {
				webUrl
				originalTitle
			}
			bestBook {
				id
				legacyId
				imageUrl
				title
				details {
					asin
					isbn
					isbn13
					language {
						name
					}
					numPages
				}
				primaryContributorEdge {
					role
					node {
						id
						name
						legacyId
						profileImageUrl
					}
				}
			}
		}
	}
}
`

func GetBookByAsin(
	ctx_ context.Context,
	client_ graphql.Client,
	asin string,
) (data_ *GetBookByAsinResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetBookByAsin",
		Query:  GetBookByAsin_Operation,
		Variables: &__GetBookByAsinInput{
			Asin: asin,
		},
	}

	data_ = &GetBookByAsinResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetBookByLegacyId.
const GetBookByLegacyId_Operation = `
query GetBookByLegacyId ($legacyId: Int!) {
	getBookByLegacyId(legacyId: $legacyId) {
		work {
			id
			legacyId
			details {
				webUrl
				originalTitle
			}
			bestBook {
				id
				legacyId
				imageUrl
				title
				details {
					asin
					isbn
					isbn13
					language {
						name
					}
					numPages
				}
				primaryContributorEdge {
					role
					node {
						id
						name
						legacyId
						profileImageUrl
					}
				}
			}
		}
	}
}
`

func GetBookByLegacyId(
	ctx_ context.Context,
	client_ graphql.Client,
	legacyId int64,
) (data_ *GetBookByLegacyIdResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetBookByLegacyId",
		Query:  GetBookByLegacyId_Operation,
		Variables: &__GetBookByLegacyIdInput{
			LegacyId: legacyId,
		},
	}

	data_ = &GetBookByLegacyIdResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by Search.
const Search_Operation = `
query Search ($query: String!) {
	getSearchSuggestions(query: $query) {
		totalCount
		edges {
			__typename
			... on SearchBookEdge {
				node {
					work {
						id
						legacyId
						bestBook {
							id
							legacyId
							imageUrl
							title
							details {
								asin
								isbn
								isbn13
								language {
									name
									__typename
								}
								numPages
								__typename
							}
							primaryContributorEdge {
								role
								node {
									id
									name
									legacyId
									profileImageUrl
									__typename
								}
							}
							__typename
						}
						__typename
					}
				}
			}
		}
	}
}
`

func Search(
	ctx_ context.Context,
	client_ graphql.Client,
	query string,
) (data_ *SearchResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "Search",
		Query:  Search_Operation,
		Variables: &__SearchInput{
			Query: query,
		},
	}

	data_ = &SearchResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
