query GetBookByAsin($asin: String!) {
  getBookByAsin(asin: $asin) {
    work {
      id
      legacyId
      details {
        webUrl
        originalTitle
      }
      bestBook {
        id
        legacyId
        imageUrl
        title
              details {
                asin
                isbn
                isbn13
                language {
                  name
                }
                numPages
              }        
        primaryContributorEdge {
          role
          node {
                  id
                  name
                  legacyId
                  profileImageUrl
          }
        }
      }
    }
  }
}

query GetBookByLegacyId($legacyId: Int!) {
  getBookByLegacyId(legacyId: $legacyId) {
    work {
      id
      legacyId
      details {
        webUrl
        originalTitle
      }
      bestBook {
        id
        legacyId
        imageUrl
        title
              details {
                asin
                isbn
                isbn13
                language {
                  name
                }
                numPages
              }        
        primaryContributorEdge {
          role
          node {
                  id
                  name
                  legacyId
                  profileImageUrl
          }
        }
      }
    }
  }
}

query Search($query: String!) {
  getSearchSuggestions(query: $query) {
    totalCount
    edges {
      ... on SearchBookEdge {
        node {
          work {
            id
            legacyId
            bestBook {
              id
              legacyId
              imageUrl
              title
              details {
                asin
                isbn
                isbn13
                language {
                  name
                  __typename
                }
                numPages
                __typename
              }
              primaryContributorEdge {
                role
                node {
                  id
                  name
                  legacyId
                  profileImageUrl
                  __typename
                }
              }
              __typename
            }
            __typename
          }
        }
      }
    }
  }
}
