query Search($query: String!) {
  getSearchSuggestions(query: $query) {
    totalCount
    edges {
      ... on SearchBookEdge {
        node {
          work {
            id
            legacyId
            bestBook {
              id
              legacyId
              imageUrl
              title
              primaryContributorEdge {
                node {
                  id
                  name
                  legacyId
                  profileImageUrl
                }
              }
            }
          }
        }
      }
    }
  }
}